import { supabase } from "./supabase";
import { WHATSAPP_ENABLED } from "./flags";

// Parent WhatsApp notification about a CHILD'S RESULTS — best-effort.
//
// ⚠️ No longer called from the browser: the automatic alerts are generated by
// the evening job (`daily-parent-alerts`), which invokes `send-whatsapp`
// server-side. Kept because that Edge Function is the one it talks to and this
// is the client-side record of its contract — and because a future screen may
// want to nudge a single parent by hand. For a message a PERSON wrote, use
// `notifyDirectMessage` below instead; it uses the other template.
//
// The actual send (and the secret provider token) live in the Supabase Edge
// Function `send-whatsapp`; from the client we only ask it to notify the parent
// of a given student. The function reads the child's name, the parent's phone
// and (for a message) the message body from the database with the service role,
// so no message content or phone number is trusted from the browser.
//
// This never throws and never blocks the UI: if WhatsApp isn't configured, the
// flag is off, or the send fails, the in-app message still went through — the
// WhatsApp nudge is an extra, not a dependency.
export async function notifyParentWhatsApp({ studentId, messageId = null, kind = "message" }) {
  if (!WHATSAPP_ENABLED || !studentId) return { ok: false, skipped: true };
  try {
    const { data, error } = await supabase.functions.invoke("send-whatsapp", {
      body: { student_id: studentId, message_id: messageId, kind },
    });
    if (error) return { ok: false, error: error.message };
    return { ok: true, data };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

/**
 * Notification for a message A PERSON wrote — to a parent OR to a colleague.
 *
 * Deliberately a DIFFERENT Edge Function and a DIFFERENT approved template from
 * the automatic alerts above. Those say "here is a lesson your child should go
 * over"; this one names the sender and quotes a short excerpt, so the recipient
 * can tell a human wrote to them rather than it being another automatic notice.
 * Mixing the two was the complaint (Maxime, 2026-09-16).
 *
 * Also the only path that can reach STAFF at all: `send-whatsapp` addresses a
 * pupil's parent and nothing else, so a message to a teacher or a referent used
 * to notify nobody.
 *
 * Only the message id travels — the sender's name, the excerpt, the recipient
 * and their phone number are all resolved server-side with the service role.
 * Best-effort: the in-app message has already landed, this is an extra.
 */
export async function notifyDirectMessage({ messageId }) {
  if (!WHATSAPP_ENABLED || !messageId) return { ok: false, skipped: true };
  try {
    const { data, error } = await supabase.functions.invoke("send-direct-message", {
      body: { message_id: messageId },
    });
    if (error) return { ok: false, error: error.message };
    return { ok: true, data };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}
